// <auto-generated />
using System;
using Day_29___Identity_Framework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Day_29___Identity_Framework.Migrations
{
    [DbContext(typeof(IdentityFrameworkTestDbContext))]
    partial class IdentityFrameworkTestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Day_29___Identity_Framework.Models.Presidents", b =>
                {
                    b.Property<int>("PresidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("InaugurationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Terms")
                        .HasColumnType("int");

                    b.HasKey("PresidentId");

                    b.ToTable("Presidents");

                    b.HasData(
                        new
                        {
                            PresidentId = 44,
                            InaugurationDate = new DateTime(2009, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Barack Obama",
                            Terms = 2
                        },
                        new
                        {
                            PresidentId = 22,
                            InaugurationDate = new DateTime(1885, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grover Cleveland",
                            Terms = 1
                        },
                        new
                        {
                            PresidentId = 24,
                            InaugurationDate = new DateTime(1893, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grover Cleveland",
                            Terms = 1
                        },
                        new
                        {
                            PresidentId = 38,
                            InaugurationDate = new DateTime(1974, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gerald Ford",
                            Terms = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
